export const MY_EXPERIENCE =
  "With over 4 years of professional experience as a Software Engineer, I've worked across fast-paced startups and established companies. My work spans designing scalable backend systems, developing responsive web applications, and building robust cloud-native infrastructure, including scalable Agentic AI Platforms for intelligent automation and agent orchestration. I've led complex projects, modernized legacy systems into fault-tolerant services, and improved system performance, all while aligning solutions with customer needs and business goals.";
export const EXPERIENCE_DETAILS = [
  {
    imageSrc: 'assets/logos/hartree-partners-logo.svg',
    imageAlt: 'Hartree Partners Logo',
    imageWidth: 90,
    imageHeight: 30,
    title: 'AI Engineer Intern',
    company: 'Hartree Partners',
    companyURL: 'https://www.hartreepartners.com/',
    summary:
      'As an AI Engineer Intern, I worked on the development of an internal AI platform used by trading and middle-office teams to build custom AI agents, bots, and interactive panels aligned with desk-specific workflows. I contributed to integrating support for multiple large language models and implementing usage and cost tracking to improve visibility and operational efficiency. I also supported the automation of internal reporting and business workflows by consolidating data from multiple sources, reducing manual effort and improving process reliability.',
    technologies: ['Python', 'Django', 'LLMs', 'Next.js', 'Celery', 'Kubernetes', 'AWS', 'VBA'],
    position: 'Internship (Co-op)',
    date: '06/2025 - 12/2025',
    location: 'New York, NY, US',
  },
  {
    imageSrc: 'assets/logos/algosec-logo.png',
    imageAlt: 'Algosec Logo',
    imageWidth: 90.05,
    title: 'Software Engineer',
    company: 'AlgoSec',
    companyURL: 'https://www.algosec.com/',
    summary:
      'In my role as a Software Engineer in the Customer Focus R&D Team, I designed and built high-performance, scalable systems, migrated legacy services using modern frameworks, and optimized deployments and network integrations to enhance reliability and efficiency. I also implemented support for additional firewall configurations, including cloud-hosted firewalls, aligning with customer setup requirements and contributing to an improved user experience and measurable business growth.',
    technologies: ['Java', 'Spring', 'Angular', 'C++', 'GNU/Linux', 'Perl', 'PostgreSQL'],
    position: 'Full-Time',
    date: '09/2022 - 08/2024',
    location: 'Gurugram, India',
  },
  {
    imageSrc: 'assets/logos/publicis-sapient-logo.png',
    imageAlt: 'Publicis Sapient Logo',
    imageWidth: 70,
    imageHeight: 38,
    title: 'Associate Software Development Engineer 2',
    company: 'Publicis Sapient',
    companyURL: 'https://www.publicissapient.com/',
    summary:
      'As an ASDE-2, I contributed to building scalable backend systems and responsive, accessible user interfaces aligned with business requirements. My work included developing a high-performance querying framework to improve API responsiveness and creating a custom charting library to optimize bundle size and significantly reduce page load times. I also developed core platform components to improve overall system performance, reliability, and deliver measurable business value.',
    technologies: [
      'Java',
      'JavaScript',
      'Spring',
      'Next.js',
      'GraphQL',
      'Microservices',
      'Kubernetes',
    ],
    position: 'Full-Time',
    date: '06/2021 - 08/2022',
    location: 'Bengaluru, India',
  },
  {
    imageSrc: 'assets/logos/gep-worldwide-logo.svg',
    imageAlt: 'GEP Worldwide Logo',
    imageWidth: 90,
    imageHeight: 30,
    title: 'Technology Intern',
    company: 'GEP Worldwide',
    companyURL: 'https://www.gep.com/',
    summary:
      'My responsibilities as an intern included building Python modules for service outage forecasting using custom kernel-based models, achieving high predictive accuracy. I also automated the extraction and classification of over 100,000 event logs per cycle using Python and Bash, improving operational efficiency. Additionally, I developed a secure Android app for QR code generation and scanning, which won an internal hackathon.',
    technologies: ['Python', 'Bash', 'Scikit-Learn', 'Java', 'Android Studio', 'Firebase'],
    position: 'Internship',
    date: '05/2020 - 07/2020',
    location: 'Navi Mumbai, India',
  },
  {
    imageSrc: 'assets/logos/ieee-logo.png',
    imageAlt: 'IEEE Logo',
    imageWidth: 90,
    title: 'LiPI: Lightweight Privacy-Preserving Data Aggregation in IoT',
    company: 'DSSRG, IIT Bhubaneswar',
    companyURL: 'https://ieeexplore.ieee.org/document/10538564',
    summary:
      "Developed and implemented LiPI, a privacy-preserving IoT/WSN data aggregation protocol, at DSSRG, IIT Bhubaneswar. Co-authored this research paper detailing this work and published at IEEE TrustCom 2023. Additionally, I optimized LiPI's performance by implementing advanced data segmentation and de-segmentation methods, resulting in a 51% performance improvement.",
    technologies: ['C++', 'Python', 'Contiki OS', 'Cooja Simulator', 'IoT/WSN'],
    position: 'Research',
    date: '01/2021 - 08/2023',
    location: 'Bhubaneswar, India',
  },
];
